### ISSUE TITLE
Polls not renedered

### ISSUE THREAD

**Issue by hassan123-dev** [huwred/Our.Community.Polls#1]
I have created a poll and added it to the home page similar to those shown in the [instructions](https://github.com/huwred/Our.Community.Polls/blob/main/gallery.md).

But on the home page instead of the poll, only "Our.Community.Polls.Models.Question" text is rendered.

**Comment by huwred** [comment]
Hi, hassan123-dev,

Could you post the code you are using to render the poll in your page template.

**Comment by hassan123-dev** [comment]
```@using Umbraco.Cms.Web.Common.PublishedModels;
@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage<ContentModels.HomePage>
@using ContentModels = Umbraco.Cms.Web.Common.PublishedModels;
@{
Layout = "Master.cshtml";
}
<!DOCTYPE HTML>
<!-- Jumbotron, w title -->
<div class="jumbotron text-center jumbotron-fluid">
	<div class="container">
		<h1 class="display-1">@Model.Value("pageTitle")</h1>
		<p>And this is <span class="font-weight-bold">only</span> the beginning.</p>
	</div>
</div>
<!-- This is where we're going to render our content -->
<div class="container">
	@Model.Value("bodyText")
</div>
<div class="container">
	@Model.Value("bodyPoll")
</div>
<!-- Footer -->
<div class="container-fluid footer">
	<div class="container">
		@Model.Value("footerText")
	</div>
</div>

**Comment by huwred** [comment]
Hi,

I would suggest that you use the ViewComponent like below
```
<div class="container">
	@await Component.InvokeAsync("Polls", Model.bodyPoll)
</div>
```
This will take care of rendering the Poll and the results once a visitor votes.

**Comment by hassan123-dev** [comment]
Thanks for your help!
Now I'm getting this error.
![image](https://github.com/huwred/Our.Community.Polls/assets/81622533/3ba05628-7522-4c01-9dfd-bb53f58160e1)

**Comment by huwred** [comment]
What is the name of your Poll component on your homepage?

**Comment by hassan123-dev** [comment]
![image](https://github.com/huwred/Our.Community.Polls/assets/81622533/63179a0e-343d-4897-a493-c6301fe06b8e)

**Comment by huwred** [comment]
Ah, ok, try 
```
<div class="container">
	@await Component.InvokeAsync("Polls", Model.BodyPoll)
</div>
```
Should be a capital B not a small b for BodyPoll

**Comment by hassan123-dev** [comment]
Thanks a lot.

Can you suggest any method by which the poll is enabled/acessible only after login?

**Comment by huwred** [comment]
That looks like it is rendering the results rather than the Poll. Have you set a start and/or end date for the Poll?

**Comment by hassan123-dev** [comment]
Poll is now rendered successfully.

Can you suggest any method by which the poll is enabled/acessible only after login?

**Comment by huwred** [comment]
There isn't anything built into the code for this, but you could just wrap it in an if statement in your template. If you inject memberManager into your template
```@inject IMemberManager _memberManager;```
You could then wrap the poll in a check like below
```
 <div class="container">
@if(_memberManager.IsLoggedIn()){
	@await Component.InvokeAsync("Polls", Model.BodyPoll)
}else{
 ... Maybe display a message here or something
}
</div>

**Comment by hassan123-dev** [comment]
Thanks a lot once again.
This makes this issue resolved.

**Comment by huwred** [comment]
You are welcome.
