### ISSUE TITLE
Poll Vote Response Showing Cached Values

### ISSUE THREAD

**Issue by keifphos** [huwred/Our.Community.Polls#2]
I have successfully installed and configured the package, and it allows me to submit a vote without issue.  However when it responds with the current vote count it shows the previous values.  If I kick the web.config to restart the site it starts showing the correct vote count, but then starts reverting to the newly cached version. The values shown in the Umbraco back office UI are consistently correct however.

**Comment by huwred** [comment]
Could you let me know what version of Umbraco you are using and I will take a look

**Comment by huwred** [comment]
I have posted a new update on nuget which should clear the cache when someone votes.

https://www.nuget.org/packages/Our.Community.Polls/2.0.4

**Comment by keifphos** [comment]
Thanks @huwred that has worked perfectly, legendary effort, thanks for all the hard work making a great package.
